version: 2.1

orbs:
  android: circleci/android@2.4.0

jobs:
  build-and-test:
    executor:
      name: android/android-machine
      tag: default

    steps:
      - checkout

      - run:
          name: Grant execute permission to gradlew
          command: chmod +x gradlew

      - restore_cache:
          keys:
            - gradle-v1-

      - run:
          name: Download dependencies
          command: ./gradlew androidDependencies

      # =========================
      # UNIT TESTS
      # =========================
      - run:
          name: Run unit tests
          command: ./gradlew lint testDebugUnitTest

      - store_test_results:
          path: app/build/test-results

      - store_artifacts:
          path: app/build/reports
          destination: reports

      # =========================
      # BUILD DEBUG APK
      # =========================
      - run:
          name: Assemble Debug APK
          command: ./gradlew assembleDebug

      - store_artifacts:
          path: app/build/outputs/apk/debug
          destination: debug-apk

      - save_cache:
          key: gradle-v1-{{ epoch }}
          paths:
            - ~/.gradle
            - ~/.android

workflows:
  build:
    jobs:
      - build-and-test